from .user import User, Role, UserRole, UserProgrammeRole, Session, AuthToken, FacultyCategory
from .programme import StudyProgramme, Course, ProgrammeCourse, CourseCoordinator
from .aol import (
    LearningGoal,
    GoalCategory,
    GoalCourseMatrix,
    GoalStaffAssignment,
    Rubric,
    RubricTrait,
    Assessment,
    AssessmentResult,
    LearningMethod,
    AssessmentMethod,
    Technology,
    ProgrammeCourseMetadata,
    CourseLearningMethod,
    CourseAssessmentMethod,
    CourseTechnology,
)
from .research import (
    Degree,
    Discipline,
    ProfessionalResponsibility,
    UserDiscipline,
    UserResponsibility,
    UserTeachingProductivity,
    IntellectualContribution,
    UserIntellectualContribution,
    ProfessionalActivity,
    PublicationType,
    PortfolioCategory,
    ExemptionType,
    UserExemption,
)

__all__ = [
    # User models
    "User",
    "Role",
    "UserRole",
    "UserProgrammeRole",
    "Session",
    "AuthToken",
    "FacultyCategory",
    # Programme models
    "StudyProgramme",
    "Course",
    "ProgrammeCourse",
    "CourseCoordinator",
    # AOL models
    "LearningGoal",
    "GoalCategory",
    "GoalCourseMatrix",
    "GoalStaffAssignment",
    "Rubric",
    "RubricTrait",
    "Assessment",
    "AssessmentResult",
    "LearningMethod",
    "AssessmentMethod",
    "Technology",
    "ProgrammeCourseMetadata",
    "CourseLearningMethod",
    "CourseAssessmentMethod",
    "CourseTechnology",
    # Research models
    "Degree",
    "Discipline",
    "ProfessionalResponsibility",
    "UserDiscipline",
    "UserResponsibility",
    "UserTeachingProductivity",
    "IntellectualContribution",
    "UserIntellectualContribution",
    "ProfessionalActivity",
    "PublicationType",
    "PortfolioCategory",
    "ExemptionType",
    "UserExemption",
]
